mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
ipv6: true
log-level: error
keep-alive-interval: 30
find-process-mode: off
external-controller: 127.0.0.1:9090
secret: "123456"
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
profile:
  store-selected: true
  store-fake-ip: true
unified-delay: true
tcp-concurrent: true
routing-mark: 6666
global-client-fingerprint: random
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 24
#自定义 geodata url
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
global-ua: clash.meta
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: false
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - "Mijia Cloud"

tun:
  enable: true
  stack: mixed # or gvisor system
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true

proxy-providers:
  MYOWN: 
    type: http
    url: "MyownMETA订阅" 
    interval: 7200
    path: ./Proxy/MyownMETA.yaml 
    health-check:
      enable: false
      interval: 300
      url: http://www.google.com/generate_204
      
proxy-groups:
  - name: "最终选择"
    type: select
    proxies:
      - DIRECT
      - PROXY

  - name: "PROXY"
    type: select
    proxies:
      - MY

  - name: "MY"
    type: select
    use:
      - MYOWN
    url: http://www.google.com/generate_204
    # interval: 60
    # tolerance: 100

  - name: "DNS-PROXY"
    type: select
    proxies:
      - PROXY
      - DIRECT
    url: http://www.google.com/generate_204
    # interval: 60
    # tolerance: 100

rule-providers:
  ClashReject:
    type: http
    behavior: classical
    path: ./ruleSet/ClashReject.yaml
    url: "https://raw.githubusercontent.com/styxiik/myrules/main/Clash/ClashReject.yaml"
    interval: 7200

  ClashProxy:
    type: http
    behavior: classical
    path: ./ruleSet/ClashProxy.yaml
    url: "https://raw.githubusercontent.com/styxiik/myrules/main/Clash/ClashProxy.yaml"
    interval: 7200

  ClashDirect:
    type: http
    behavior: classical
    path: ./ruleSet/ClashDirect.yaml
    url: "https://raw.githubusercontent.com/styxiik/myrules/main/Clash/ClashDirect.yaml"
    interval: 7200

  reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  cnipv6:
    type: http
    behavior: ipcidr
    path: ./ruleSet/cnipv6.yaml
    url: "https://raw.githubusercontent.com/styxiik/myrules/main/Clash/cnipv6.txt"
    interval: 7200

  applications:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  cryptocurrency:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cryptocurrency/Cryptocurrency.yaml"
    path: ./ruleset/cryptocurrency.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cfip:
    type: http
    behavior: ipcidr
    path: ./ruleSet/cfip.yaml
    url: "https://raw.githubusercontent.com/styxiik/myrules/main/Clash/cfip.txt"
    interval: 7200

  googleip:
    type: http
    behavior: ipcidr
    path: ./ruleSet/googleip.yaml
    url: "https://raw.githubusercontent.com/styxiik/myrules/main/Clash/googleip.txt"
    interval: 7200

  cloudfrontip:
    type: http
    behavior: ipcidr
    path: ./ruleSet/cloudfrontip.yaml
    url: "https://raw.githubusercontent.com/styxiik/myrules/main/Clash/cft.txt"
    interval: 7200

  geolocation-!cn:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.yaml"
    path: ./geolocation-uncn.yaml
    interval: 86400
    
rules:
  - AND,((DST-PORT,443),(NETWORK,UDP)),REJECT
  - AND,((DST-PORT,9993),(NETWORK,UDP)),DIRECT
  - AND,((DST-PORT,445),(NETWORK,TCP)),DIRECT
  - AND,((DST-PORT,7680),(NETWORK,tcp)),REJECT
  - AND,((DST-PORT,161),(NETWORK,UDP)),REJECT
  - RULE-SET,ClashReject,REJECT,no-resolve
  - RULE-SET,ClashProxy,PROXY,no-resolve
  - RULE-SET,ClashDirect,DIRECT,no-resolve
  - DOMAIN-SUFFIX,cn,DIRECT
  # - RULE-SET,reject,REJECT,no-resolve
  - RULE-SET,private,DIRECT,no-resolve
  - RULE-SET,direct,DIRECT,no-resolve
  - RULE-SET,icloud,DIRECT,no-resolve
  - RULE-SET,apple,DIRECT,no-resolve
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,cnipv6,DIRECT
  - RULE-SET,applications,DIRECT
  - GEOIP,CN,DIRECT
  - GEOIP,LAN,DIRECT
  - RULE-SET,gfw,PROXY,no-resolve
  - RULE-SET,cryptocurrency,PROXY,no-resolve
  - RULE-SET,google,PROXY,no-resolve
  - RULE-SET,greatfire,PROXY,no-resolve
  - RULE-SET,telegramcidr,PROXY,no-resolve
  - RULE-SET,cfip,PROXY
  - RULE-SET,googleip,PROXY
  - RULE-SET,cloudfrontip,DIRECT
  - MATCH,最终选择
dns:
  enable: true
  listen: :53
  ipv6: true
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - system
  nameserver:
    - https://doh.pub/dns-query
    - tls://dot.pub:853
    - https://223.5.5.5/dns-query#h3=true
    - tls://223.5.5.5:853
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "rule-set:direct,icloud,apple,applications,private":
      - https://doh.pub/dns-query
      - tls://dot.pub:853
      - https://223.5.5.5/dns-query#h3=true
      - tls://223.5.5.5:853
    "rule-set:geolocation-!cn":
      - "https://1.1.1.1/dns-query#DNS-PROXY"
      - "https://8.8.8.8/dns-query#DNS-PROXY"
      - "tls://8.8.4.4:853#DNS-PROXY"
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.githubusercontent.com'
      - '+.googlevideo.com'
      - '+.msftconnecttest.com'
      - '+.msftncsi.com'
  #fake-ip or redir-host
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  use-hosts: true
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time-ios.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    - '+.qq.com'
    - '+.tencent.com'
    - '+.srv.nintendo.net'
    - '*.n.n.srv.nintendo.net'
    - '+.cdn.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    - 'xbox.*.microsoft.com'
    - 'xnotify.xboxlive.com'
    - '+.battlenet.com.cn'
    - '+.wotgame.cn'
    - '+.wggames.cn'
    - '+.wowsgame.cn'
    - '+.wargaming.net'
    - 'proxy.golang.org'
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - 'heartbeat.belkin.com'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - 'mesu.apple.com'
    - 'swscan.apple.com'
    - 'swquery.apple.com'
    - 'swdownload.apple.com'
    - 'swcdn.apple.com'
    - 'swdist.apple.com'
    - 'lens.l.google.com'
    - 'stun.l.google.com'
    - 'na.b.g-tun.com'
    - '+.nflxvideo.net'
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.ff14.sdo.com'
    - 'ff.dorado.sdo.com'
    - '*.mcdn.bilivideo.cn'
    - '+.media.dssott.com'
    - 'shark007.net'
    - 'Mijia Cloud'
    - '+.cmbchina.com'
    - '+.cmbimg.com'
    - 'local.adguard.org'
    - '+.sandai.net'
    - '+.n0808.com'
    - '+.uu.163.com'
    - 'ps.res.netease.com'
    - '+.cmbchina.com'
    - '+.apple.com'
    - '+.icloud.com'
    - '+.mzstatic.com'
    - '+.cdn-apple.com'
    - '+.haowu.link'
    - '+.cmbimg.com'
    - '+.digitalcertvalidation.com'
    - '+.zhuanzfx.com'
    - '+.cib.com.cn'
    - '+.dcocsp.com'
    - '+.95559.com.cn'
    - '+.bankcomm.com'
    - '+.digicert.com'
    - '+.pingan.com.cn'
    - '+.stun.l.google.com'
    - '+.zerotier.com'
    - 'al.mydomain1'
    - 'alist.mydomain1'
    - 'nec.mydomain1'
    - 'lo.mydomain1'
hosts:
   'dns.google': 8.8.8.8
