geodata-mode: true
tcp-concurrent: false
sniffer:
  enable: false
  sniffing:
    - tls
    - http
  skip-domain:
    - 'Mijia Cloud'
    - 'dlg.io.mi.com'
    - '+.apple.com'
    - '*.baidu.com'
    - '+.jd.com'
  force-domain:
  # - '+'                        #去掉注释后等于全局嗅探
    - 'google.com'
    - '+.netflix.com'
    - '+.nflxvideo.net'
    - '+.amazonaws.com'
    - '+.media.dssott.com'
  port-whitelist:
  - 80
  - 443
# - 8000-9000
# 分割线......
bypass:
  - "www.msftconnecttest.com"
  - "ipv6.msftconnecttest.com"
  - "dns.msftncsi.com"
  - "131.107.255.255"
mixed-port: 7890
auto-redir:
  enable: true
  auto-route: true
allow-lan: true
bind-address: '*'
mode: rule
ipv6: true
log-level: error
external-controller: 127.0.0.1:9090
profile:
  store-selected: false
  store-fake-ip: true
tun:
  enable: true
  stack: gvisor # or gvisor system
  dns-hijack:
    - any:53
    - tcp://any:53
    - tcp://any:5353
  auto-route: true
  auto-detect-interface: true

proxy-providers:
  MYOWN: 
    type: http
    url: "MyownMETA订阅" 
    interval: 7200
    path: ./Proxy/MyownMETA.yaml 
    health-check:
      enable: true
      interval: 300
      url: http://www.google.com/generate_204

  Backup: 
    type: http
    url: "bbClash订阅" 
    interval: 7200
    path: ./Proxy/Backup.yaml 
    health-check:
      enable: true
      interval: 300
      url: http://www.google.com/generate_204
      
proxy-groups:
  - name: "最终选择"
    type: select
    proxies:
      - DIRECT
      - PROXY

  - name: "PROXY"
    type: select
    proxies:
      - MY
      - BK

  - name: "MY"
    type: select
    use:
      - MYOWN
    url: http://www.google.com/generate_204
    interval: 60
    tolerance: 100

  - name: "BK"
    type: select
    use:
      - Backup
    url: http://www.google.com/generate_204
    interval: 60
    tolerance: 100

rule-providers:
  ClashReject:
    type: http
    behavior: classical
    path: ./ruleSet/ClashReject.yaml
    url: "https://raw.githubusercontent.com/styxiik/myrules/main/Clash/ClashReject.yaml"
    interval: 7200

  ClashDirect:
    type: http
    behavior: classical
    path: ./ruleSet/ClashDirect.yaml
    url: "https://raw.githubusercontent.com/styxiik/myrules/main/Clash/ClashDirect.yaml"
    interval: 7200

  ClashProxy:
    type: http
    behavior: classical
    path: ./ruleSet/ClashProxy.yaml
    url: "https://raw.githubusercontent.com/styxiik/myrules/main/Clash/ClashProxy.yaml"
    interval: 7200

  reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  cnipv6:
    type: http
    behavior: ipcidr
    path: ./ruleSet/cnipv6.yaml
    url: "https://raw.githubusercontent.com/styxiik/myrules/main/Clash/cnipv6.txt"
    interval: 7200

  applications:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  cryptocurrency:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cryptocurrency/Cryptocurrency.yaml"
    path: ./ruleset/cryptocurrency.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cfip:
    type: http
    behavior: ipcidr
    path: ./ruleSet/cfip.yaml
    url: "https://raw.githubusercontent.com/styxiik/myrules/main/Clash/cfip.txt"
    interval: 7200

  googleip:
    type: http
    behavior: ipcidr
    path: ./ruleSet/googleip.yaml
    url: "https://raw.githubusercontent.com/styxiik/myrules/main/Clash/googleip.txt"
    interval: 7200

#delete
    
rules:
  - AND,((DST-PORT,443),(NETWORK,UDP)),REJECT
  - AND,((DST-PORT,9993),(NETWORK,UDP)),PROXY
  - AND,((DST-PORT,445),(NETWORK,TCP)),DIRECT
  - AND,((DST-PORT,161),(NETWORK,UDP)),REJECT
  - RULE-SET,ClashReject,REJECT
  - RULE-SET,ClashDirect,DIRECT
  - RULE-SET,ClashProxy,PROXY
  - RULE-SET,reject,REJECT
  - RULE-SET,private,REJECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,cnipv6,DIRECT
  - RULE-SET,applications,DIRECT
  - GEOIP,CN,DIRECT
  - RULE-SET,gfw,PROXY
  - RULE-SET,cryptocurrency,PROXY
  - RULE-SET,google,PROXY
  - RULE-SET,greatfire,PROXY
  - RULE-SET,telegramcidr,PROXY
  - RULE-SET,cfip,PROXY
  - RULE-SET,googleip,PROXY
  - MATCH,最终选择
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - https://doh.pub/dns-query
    - tls://dot.pub:853
    - https://223.5.5.5/dns-query
    - tls://223.5.5.5:853
  fallback:
    - G_DNS
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.google.com.hk'
      - '+.facebook.com'
      - '+.youtube.com'
  #fake-ip or redir-host
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time-ios.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - 'msftconnecttest.com'
    - 'msftncsi.com'
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    - '+.srv.nintendo.net'
    - '*.n.n.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    - 'xbox.*.microsoft.com'
    - 'xnotify.xboxlive.com'
    - '+.battlenet.com.cn'
    - '+.wotgame.cn'
    - '+.wggames.cn'
    - '+.wowsgame.cn'
    - '+.wargaming.net'
    - 'proxy.golang.org'
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - 'heartbeat.belkin.com'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - 'mesu.apple.com'
    - 'swscan.apple.com'
    - 'swquery.apple.com'
    - 'swdownload.apple.com'
    - 'swcdn.apple.com'
    - 'swdist.apple.com'
    - 'lens.l.google.com'
    - 'stun.l.google.com'
    - '+.nflxvideo.net'
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.ff14.sdo.com'
    - 'ff.dorado.sdo.com'
    - '*.mcdn.bilivideo.cn'
    - '+.media.dssott.com'
    - 'shark007.net'
    - 'Mijia Cloud'
    - '+.cmbchina.com'
    - '+.cmbimg.com'
    - '+.cmbchina.com'
    - '+.haowu.link'
    - '+.cmbimg.com'
    - '+.digitalcertvalidation.com'
    - '+.zhuanzfx.com'
    - '+.cib.com.cn'
    - '+.dcocsp.com'
    - '+.95559.com.cn'
    - '+.bankcomm.com'
    - '+.digicert.com'
    - '+.pingan.com.cn'
    - '+.stun.l.google.com'
hosts:
   'dns.google': 8.8.8.8
   '+.workers.dev': 104.17.151.180
   '+.cloudflare.com': 104.17.151.180
   '+.cloudflareworkers.com': 104.17.151.180
